# Generated by Django 2.1.4 on 2020-05-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_data_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='reports',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY')], default='Choose', max_length=8),
        ),
    ]
