# Generated by Django 2.1.4 on 2020-05-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20200502_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='team_lead',
            field=models.CharField(choices=[('Raktima Mitra', 'Raktima Mitra'), ('Akansha', 'Akansha')], default=True, max_length=11),
        ),
    ]
