# Generated by Django 2.1.4 on 2020-05-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_data_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='team_lead',
            field=models.CharField(choices=[('Raktima Mitra', 'Raktima Mitra'), ('Akansha', 'Akansha'), ('Amitesh Ranjan', 'Amitesh Ranjan'), ('Sheetal', 'Sheetal'), ('Kanika', 'Kanika'), ('Ajeet', 'Ajeet'), ('Shekar', 'Shekar')], default=True, max_length=11),
        ),
    ]
