# Generated by Django 2.1.4 on 2020-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20200502_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.CharField(default='20/05/2019', max_length=20),
        ),
    ]
