# Generated by Django 2.1.4 on 2020-05-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_remove_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='team_lead',
            field=models.CharField(blank=True, choices=[('Raktima Mitra', 'Raktima Mitra'), ('Akansha', 'Akansha'), ('Amitesh Ranjan', 'Amitesh Ranjan'), ('Sheetal', 'Sheetal'), ('Kanika', 'Kanika'), ('Ajeet', 'Ajeet'), ('Shekar', 'Shekar')], max_length=25),
        ),
    ]
